{
 "title": "vLLM",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vllm_instance",
    "label": "vLLM Instance",
    "query": {
     "query": "label_values({service=\"vllm\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "vllm_instance" },
  {
   "title": "vLLM Instance Info",
   "type": "table",
   "gridPos": { "h": 21, "w": 4, "x": 0, "y": 1 },
   "targets": [
    { "expr": "vllm:cache_config_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vLLM Running Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    { "expr": "vllm:num_requests_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vLLM Waiting Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 9 },
   "targets": [
    { "expr": "vllm:num_requests_waiting", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Successful Requests",
   "type": "stat",
   "description": "Count of successfully processed requests",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vllm:request_success_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Generation Tokens",
   "type": "stat",
   "description": "Number of generation tokens processed",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vllm:generation_tokens_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Prompt Tokens",
   "type": "stat",
   "description": "Number of prefill tokens processed.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vllm:prompt_tokens_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Preemptions",
   "type": "stat",
   "description": "Cumulative number of preemptions from the engine",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vllm:num_preemptions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "KV Cache Util.",
   "type": "gauge",
   "description": "GPU KV-cache usage. 1 means 100 percent usage.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vllm:gpu_cache_usage_perc", "legendFormat": "__auto" }
   ]
  }
 ]
}