name: Linting

on:
  push:
    branches:
    - develop
    - 'docs/*'
    - 'roc**'
  pull_request:
    branches:
    - develop
    - 'docs/*'
    - 'roc**'

jobs:
  call-workflow-passing-data:
    name: Documentation
    uses: ROCm/rocm-docs-core/.github/workflows/linting.yml@develop

